name: Daily Python Script

on:
  schedule:
    - cron: "55 7 * * *"

jobs:
  run_python_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Python script
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          QUOTE_API_KEY: ${{ secrets.QUOTE_API_KEY }}
          RECEIVER_EMAIL: ${{ env.RECEIVER_EMAIL }}
          EMAIL_SUBJECT: ${{ env.EMAIL_SUBJECT }}
        run: python main.py
