name: Daily Python Script

on: push

jobs:
  run_python_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Dump env variables
        env:
          ENV_CONTEXT: ${{ toJson(env) }}
          VARS_CONTEXT: ${{ toJson(vars) }}
        run: |
          echo "$ENV_CONTEXT"
          echo "$VARS_CONTEXT"

      - name: Run Python script
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          QUOTE_API_KEY: ${{ secrets.QUOTE_API_KEY }}
          RECEIVER_EMAIL: ${{ vars.RECEIVER_EMAIL }}
          EMAIL_SUBJECT: ${{ vars.EMAIL_SUBJECT }}
        run: python main.py
